# Generated by Django 3.2.8 on 2023-04-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='问题标题')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='问题路径')),
                ('link', models.URLField(verbose_name='问题链接')),
                ('statement', models.TextField(verbose_name='问题描述')),
                ('num_submissions', models.IntegerField(default=0)),
                ('num_ac', models.IntegerField(default=0)),
                ('num_wa', models.IntegerField(default=0)),
                ('num_re', models.IntegerField(default=0)),
                ('num_tle', models.IntegerField(default=0)),
                ('num_ce', models.IntegerField(default=0)),
                ('data_added', models.DateTimeField(auto_now_add=True)),
                ('time_limit', models.IntegerField(default=1)),
                ('score', models.IntegerField(default=1)),
                ('source', models.CharField(max_length=255)),
                ('num_tests', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': '问题集',
                'verbose_name_plural': '问题集',
            },
        ),
    ]
