# Generated by Django 3.2.8 on 2023-04-14 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0002_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='score',
            field=models.IntegerField(default=1),
        ),
    ]
