# Generated by Django 3.2.8 on 2023-04-25 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0003_submission_testcase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='博客题目')),
                ('idcode', models.CharField(default=1, max_length=20, unique=True, verbose_name='博客路径')),
                ('link', models.URLField(default=-1, verbose_name='博客链接')),
                ('content', models.TextField(verbose_name='博客内容')),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='machine.coder')),
            ],
            options={
                'verbose_name': '博客集',
                'verbose_name_plural': '博客集',
            },
        ),
    ]
