# Generated by Django 3.2.8 on 2023-04-17 07:27

from django.db import migrations, models
import django.db.models.deletion
import machine.models.problem.testcase


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0003_problem_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coder',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.AlterModelOptions(
            name='problem',
            options={'verbose_name': '问题集', 'verbose_name_plural': '问题集'},
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_file', models.FileField(upload_to=machine.models.problem.testcase.in_upload_path, verbose_name='输入文件')),
                ('output_file', models.FileField(upload_to=machine.models.problem.testcase.out_upload_path, verbose_name='输出文件')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine.problem', verbose_name='问题')),
            ],
            options={
                'verbose_name': '测试数据',
                'verbose_name_plural': '测试数据',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NT', 'Not tested'), ('CE', 'Compile Error'), ('TLE', 'Time Limit Error'), ('RE', 'Runtime Error'), ('AC', 'Accepted'), ('WA', 'Wrong Answer')], default='NT', max_length=2)),
                ('lang', models.CharField(choices=[('C', 'GNU C'), ('CPP', 'GNU C++')], default='CPP', max_length=4)),
                ('code', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('private', models.BooleanField(default=True)),
                ('problem', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='machine.problem')),
                ('submitter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='machine.coder')),
            ],
            options={
                'verbose_name': '提交结果',
                'verbose_name_plural': '提交结果',
            },
        ),
    ]
