# Generated by Django 3.2.8 on 2023-04-21 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0004_auto_20230417_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('NT', 'Not tested'), ('CE', 'Compile Error'), ('TL', 'Time Limit Error'), ('RE', 'Runtime Error'), ('AC', 'Accepted'), ('WA', 'Wrong Answer')], default='NT', max_length=2),
        ),
    ]
