# Generated by Django 3.2.8 on 2023-04-25 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0004_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='machine.coder')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='machine.post')),
            ],
            options={
                'verbose_name': '评论集',
                'verbose_name_plural': '评论集',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='machine.coder')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='machine.post')),
            ],
            options={
                'verbose_name': '点赞集',
                'verbose_name_plural': '点赞集',
                'unique_together': {('post', 'author')},
            },
        ),
    ]
