# Generated by Django 3.2.8 on 2023-04-25 15:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0005_comment_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gamename', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('link', models.URLField(blank=True, max_length=256)),
                ('timestart', models.DateTimeField(default=django.utils.timezone.now)),
                ('timeend', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.IntegerField(default=0)),
                ('gamestatement', models.TextField(default=0)),
                ('gamehard', models.IntegerField(default=0)),
            ],
        ),
    ]
