# Generated by Django 3.2.8 on 2023-04-21 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0005_alter_submission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='ac_num',
            field=models.IntegerField(default=0),
        ),
    ]
