# Generated by Django 3.2.8 on 2023-04-25 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0008_gamesubmission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name': '比赛信息', 'verbose_name_plural': '比赛信息'},
        ),
        migrations.AlterModelOptions(
            name='gameproblem',
            options={'verbose_name': '比赛题目对应表', 'verbose_name_plural': '比赛题目对应表'},
        ),
        migrations.AlterModelOptions(
            name='gamesubmission',
            options={'verbose_name': '比赛提交状态', 'verbose_name_plural': '比赛提交状态'},
        ),
        migrations.CreateModel(
            name='GameRk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalac', models.IntegerField(default=0)),
                ('failtime', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine.game')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='machine.coder')),
                ('playersubs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='machine.gamesubmission')),
            ],
            options={
                'verbose_name': '比赛排名信息',
                'verbose_name_plural': '比赛排名信息',
            },
        ),
    ]
