# Generated by Django 3.2.8 on 2023-04-22 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0009_post_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='machine.coder')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='machine.post')),
            ],
            options={
                'verbose_name': '评论集',
                'verbose_name_plural': '评论集',
            },
        ),
    ]
