# Generated by Django 3.2.8 on 2023-04-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0009_auto_20230426_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='gamenum',
            field=models.IntegerField(default=0),
        ),
    ]
