# Generated by Django 3.2.8 on 2023-04-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0011_gameproblem_passnum'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesubmission',
            name='lang',
            field=models.CharField(choices=[('C', 'GNU C'), ('CPP', 'GNU C++'), ('JAVA', 'JAVAC'), ('PYTHON3', 'PYTH3')], default='CPP', max_length=10),
        ),
        migrations.AlterField(
            model_name='gamesubmission',
            name='result',
            field=models.CharField(choices=[('NT', 'Not tested'), ('CE', 'Compile Error'), ('TLE', 'Time Limit Error'), ('RE', 'Runtime Error'), ('AC', 'Accepted'), ('WA', 'Wrong Answer')], default='NT', max_length=3),
        ),
    ]
