# Generated by Django 3.2.8 on 2023-04-22 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0011_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='code',
            field=models.CharField(default=-1, max_length=20, unique=True, verbose_name='问题路径'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='博客内容'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, verbose_name='博客题目'),
        ),
    ]
