# Generated by Django 3.2.8 on 2023-04-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0013_gameproblem_addnum'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesubmission',
            name='totaltime',
            field=models.IntegerField(default=0),
        ),
    ]
