# Generated by Django 3.2.8 on 2023-04-27 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0014_gamesubmission_totaltime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamesubmission',
            old_name='totaltime',
            new_name='nowtime',
        ),
    ]
