# Generated by Django 3.2.8 on 2023-04-25 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0015_auto_20230423_0509'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gamename', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('link', models.URLField(blank=True, max_length=256)),
                ('timestart', models.DateTimeField()),
                ('timeend', models.DateTimeField()),
                ('status', models.IntegerField(default=0)),
                ('gamestatement', models.TextField()),
                ('gamehard', models.IntegerField(default=0)),
            ],
        ),
    ]
