# Generated by Django 3.2.8 on 2023-04-25 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0016_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('result', models.CharField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine.game')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine.problem')),
                ('submitter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='machine.coder')),
            ],
        ),
        migrations.CreateModel(
            name='GameProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine.game')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine.problem')),
            ],
        ),
    ]
