# Generated by Django 3.2.8 on 2023-04-25 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0018_auto_20230425_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesubmission',
            name='code',
            field=models.TextField(default=-1),
        ),
        migrations.AlterField(
            model_name='gamesubmission',
            name='result',
            field=models.CharField(default=-1),
        ),
    ]
