# Generated by Django 3.2.8 on 2023-05-02 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0019_remove_gamerk_playersubs'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameCoder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passnum', models.IntegerField(default=0)),
                ('failtime', models.IntegerField(default=0)),
                ('coder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='machine.coder')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine.game')),
            ],
            options={
                'verbose_name': '比赛用户对应表',
                'verbose_name_plural': '比赛用户对应表',
            },
        ),
    ]
