# Generated by Django 3.2.8 on 2023-04-25 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0020_delete_gamesubmission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameProblem',
        ),
    ]
