# Generated by Django 3.2.8 on 2023-05-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0020_gamecoder'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='codernum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='problemnum',
            field=models.IntegerField(default=0),
        ),
    ]
