# Generated by Django 3.2.8 on 2023-04-25 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0021_delete_gameproblem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Game',
        ),
    ]
