# Generated by Django 3.2.8 on 2023-05-02 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0021_auto_20230502_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameproblem',
            name='passnum',
        ),
    ]
