# Generated by Django 3.2.8 on 2023-05-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0022_remove_gameproblem_passnum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamecoder',
            name='failtime',
        ),
        migrations.RemoveField(
            model_name='gamecoder',
            name='passnum',
        ),
        migrations.RemoveField(
            model_name='gameproblem',
            name='addnum',
        ),
        migrations.AddField(
            model_name='gamerk',
            name='alltime',
            field=models.IntegerField(default=0),
        ),
    ]
