# Generated by Django 3.2.8 on 2023-04-25 04:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0023_game_gameproblem_gamesubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='timeend',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='game',
            name='timestart',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='gamesubmission',
            name='code',
            field=models.TextField(default='请在此写下代码'),
        ),
        migrations.AlterField(
            model_name='gamesubmission',
            name='result',
            field=models.CharField(default='NT', max_length=20),
        ),
    ]
