# Generated by Django 3.2.8 on 2023-04-25 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0025_alter_submission_problem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='code',
            field=models.TextField(),
        ),
    ]
