# Generated by Django 3.2.8 on 2023-05-05 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0026_alter_post_idcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='link',
        ),
    ]
