# Generated by Django 3.2.8 on 2023-04-25 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0026_alter_submission_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameproblem',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine.problem'),
        ),
        migrations.AlterField(
            model_name='gamesubmission',
            name='code',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='gamesubmission',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine.problem'),
        ),
        migrations.AlterField(
            model_name='gamesubmission',
            name='result',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='gamesubmission',
            name='submitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine.coder'),
        ),
    ]
