# Generated by Django 3.2.8 on 2023-05-05 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0028_alter_post_idcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coder',
            name='avatar',
            field=models.ImageField(default='avatar/default_avatar.png', upload_to='avatar/'),
        ),
    ]
