# Generated by Django 3.2.8 on 2023-05-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0029_alter_coder_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coder',
            name='avatar',
            field=models.ImageField(default='avatar/default_avatar.jpg', upload_to='avatar/'),
        ),
    ]
